protocol1 = {
    "Alarm LED": [17, 1],
    "Baud Rate": [4, 1],
    "CCW Angle Limit": [8, 2],
    "CW Angle Limit": [6, 2],
    "Firmware Version": [2, 1],
    "ID": [3, 1],
    "Max Torque": [14, 2],
    "Max Voltage Limit": [13, 1],
    "Min Voltage Limit": [12, 1],
    "Model Number": [0, 2],
    "Return Delay Time": [5, 1],
    "Shutdown": [18, 1],
    "Status Return Level": [16, 1],
    "Temperature Limit": [11, 1],
    "CCW Compliance Margin": [27, 1],
    "CCW Compliance Slope": [29, 1],
    "CW Compliance Margin": [26, 1],
    "CW Compliance Slope": [28, 1],
    "Goal Position": [30, 2],
    "LED": [25, 1],
    "Lock": [47, 1],
    "Moving": [46, 1],
    "Moving Speed": [32, 2],
    "Present Load": [40, 2],
    "Present Position": [36, 2],
    "Present Speed": [38, 2],
    "Present Temperature": [43, 1],
    "Present Voltage": [42, 1],
    "Punch": [48, 2],
    "Registered": [44, 1],
    "Torque Enable": [24, 1],
    "Torque Limit": [34, 2],
}

protocol2 = {
    "Acceleration Limit": [40, 4],
    "Baud Rate": [8, 1],
    "Current Limit": [38, 2],
    "Drive Mode": [10, 1],
    "Firmware Version": [6, 1],
    "Homing Offset": [20, 4],
    "ID": [7, 1],
    "Max Position Limit": [48, 4],
    "Max Voltage Limit": [32, 2],
    "Min Position Limit": [52, 4],
    "Min Voltage Limit": [34, 2],
    "Model Information": [2, 4],
    "Model Number": [0, 2],
    "Moving Threshold": [24, 4],
    "Operating Mode": [11, 1],
    "PWM Limit": [36, 2],
    "Protocol Version": [13, 1],
    "Return Delay Time": [9, 1],
    "Secondary(Shadow) ID": [12, 1],
    "Shutdown": [63, 1],
    "Temperature Limit": [31, 1],
    "Velocity Limit": [44, 4],
    "BUS Watchdog": ["98", "1"],
    "Feedforward 1st Gain": ["90", "2"],
    "Feedforward 2nd Gain": ["88", "2"],
    "Goal Current": ["102", "2"],
    "Goal PWM": ["100", "2"],
    "Goal Position": ["116", "4"],
    "Goal Velocity": ["104", "4"],
    "Hardware Error Status": ["70", "1"],
    "LED": ["65", "1"],
    "Moving": ["122", "1"],
    "Moving Status": ["123", "1"],
    "Position D Gain": ["80", "2"],
    "Position I Gain": ["82", "2"],
    "Position P Gain": ["84", "2"],
    "Position Trajectory": ["140", "4"],
    "Present Current": ["126", "2"],
    "Present Input Voltage": ["144", "2"],
    "Present PWM": ["124", "2"],
    "Present Position": ["132", "4"],
    "Present Temperature": ["146", "1"],
    "Present Velocity": ["128", "4"],
    "Profile Acceleration": ["108", "4"],
    "Profile Velocity": ["112", "4"],
    "Realtime Tick": ["120", "2"],
    "Registered Instruction": ["69", "1"],
    "Status Return Level": ["68", "1"],
    "Torque Enable": ["64", "1"],
    "Velocity I Gain": ["76", "2"],
    "Velocity P Gain": ["78", "2"],
    "Velocity Trajectory": ["136", "4"],
}

protocol1_mx = {
    "Alarm LED": [17, 1],
    "Baud Rate": [4, 1],
    "CCW Angle Limit": [8, 2],
    "CW Angle Limit": [6, 2],
    "Firmware Version": [2, 1],
    "ID": [3, 1],
    "Max Torque": [14, 2],
    "Max Voltage Limit": [13, 1],
    "Min Voltage Limit": [12, 1],
    "Model Number": [0, 2],
    "Multi Turn Offset": [20, 2],
    "Resolution Divider": [22, 1],
    "Return Delay Time": [5, 1],
    "Shutdown": [18, 1],
    "Status Return Level": [16, 1],
    "Temperature Limit": [11, 1],
    "Current": [68, 2],
    "D Gain": [26, 1],
    "Goal Acceleration": [73, 1],
    "Goal Position": [30, 2],
    "Goal Torque": [71, 2],
    "I Gain": [27, 1],
    "LED": [25, 1],
    "Lock": [47, 1],
    "Moving": [46, 1],
    "Moving Speed": [32, 2],
    "P Gain": [28, 1],
    "Present Load": [40, 2],
    "Present Position": [36, 2],
    "Present Speed": [38, 2],
    "Present Temperature": [43, 1],
    "Present Voltage": [42, 1],
    "Punch": [48, 2],
    "Realtime Tick": [50, 2],
    "Registered": [44, 1],
    "Torque Ctrl Mode Enable": [70, 1],
    "Torque Enable": [24, 1],
    "Torque Limit": [34, 2],
}
